### ISSUE TITLE
build fails outside of eic-shell

### ISSUE THREAD

**Issue by faustus123** [eic/EDM4eic#8] opened 2022-09-07 17:10 UTC
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): v1.0.0
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs? RHEL7
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
This is done outside of eic-shell

1. cmake build against PODIO v00-15 and edm4hep v00-06

### Expected Result: (what do you expect when you execute the steps above)
Package builds

### Actual Result: (what do you get when you execute the steps above)

The build fails with the message below indicating it is unable to find the edm4hep/Vector3f.h file. Messages during the cmake stage indicate it is finding the correct podio and edm4hep versions. I also confirmed that the the file exists in the edm4hep build.

I suspect this is due to development and testing being done entirely within eic-shell which has edm4hep include files installed (symlinked) in /usr/local which is in the include path by default. Building in an environment where edm4hep is installed outside of  common directories like /usr/local will need to have the edm4hep include directory added.

[  1%] Building CXX object CMakeFiles/edm4eic.dir/src/ReconstructedParticle.cc.o
/opt/rh/devtoolset-9/root/usr/bin/c++ -Dedm4eic_EXPORTS -I/home/davidl/work/2022.07.11.EICrecon/EICTOP/root/root-6.26.04/include -I/home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build -isystem /home/davidl/work/2022.07.11.EICrecon/EICTOP/PODIO/v00-15/install/include -std=c++17 -pipe -fsigned-char -pthread -fPIC -std=gnu++2a -MD -MT CMakeFiles/edm4eic.dir/src/ReconstructedParticle.cc.o -MF CMakeFiles/edm4eic.dir/src/ReconstructedParticle.cc.o.d -o CMakeFiles/edm4eic.dir/src/ReconstructedParticle.cc.o -c /home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build/src/ReconstructedParticle.cc
In file included from /home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build/edm4eic/ReconstructedParticleObj.h:7,
                 from /home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build/edm4eic/ReconstructedParticle.h:6,
                 from /home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build/src/ReconstructedParticle.cc:4:
/home/davidl/work/2022.07.11.EICrecon/EICTOP/edm4eic/v1.0.0/build/edm4eic/ReconstructedParticleData.h:7:10: fatal error: edm4hep/Vector3f.h: No such file or directory
    7 | #include "edm4hep/Vector3f.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by DraTeots** [comment] 2022-09-07 17:17
Hm... This works for me except I had to update to cmake 3.24

**Comment by faustus123** [comment] 2022-09-07 17:18
Right. I'm also using that, but that was not the issue. It is that the edm4hep include directory is not found.

**Comment by veprbl** [comment] 2022-09-07 21:04
I can reproduce

**Comment by veprbl** [comment] 2022-09-08 13:46
Actually, this should have been fixed in #6. @faustus123 Can you try on master?

**Closed** 2022-09-08 13:51 UTC
